# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_order_orderentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extras',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
