# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_auto_20160418_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rms.Restaurant'),
            preserve_default=False,
        ),
    ]
