# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_order_restaurant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='MyUser',
        ),
    ]
