# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0003_order_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=15910685106, max_length=16),
            preserve_default=False,
        ),
    ]
