# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_auto_20160422_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'permissions': (('view_restaurant', 'Can view restaurant'),)},
        ),
    ]
