# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ID', '\u672a\u652f\u4ed8'), ('PD', '\u5df2\u652f\u4ed8'), ('CD', '\u5df2\u53d6\u6d88'), ('RG', '\u9000\u6b3e\u4e2d'), ('RD', '\u5df2\u9000\u6b3e'), ('FD', '\u5df2\u5b8c\u6210')], default='ID', max_length=2),
        ),
    ]
